//---------------------------------------------------------
// Copyright 2016 Ontario Institute for Cancer Research
// Written by Jared Simpson (jared.simpson@oicr.on.ca)
//---------------------------------------------------------
//
// nanopolish_builtin_models -- collection of models
// that are compiled directly into the nanopolish
// binary to avoid users having to pass them at runtime
//
#ifndef NANOPOLISH_BUILTIN_MODELS
#define NANOPOLISH_BUILTIN_MODELS

#include "nanopolish_poremodel.h"

// Autogenerated from convert_all_models.py
#include "builtin_models/c_p1_007_ecoli_er2925_pcr_MSssI_r9_timp_061716_alphabet_cpg_model.inl"
#include "builtin_models/c_p1_007_ont_alphabet_nucleotide_5mer_model.inl"
#include "builtin_models/c_p1_007_ont_alphabet_nucleotide_model.inl"
#include "builtin_models/c_p2_007_ecoli_er2925_pcr_MSssI_r9_timp_061716_alphabet_cpg_model.inl"
#include "builtin_models/c_p2_007_ont_alphabet_nucleotide_5mer_model.inl"
#include "builtin_models/c_p2_007_ont_alphabet_nucleotide_model.inl"
#include "builtin_models/t_007_ecoli_er2925_pcr_MSssI_r9_timp_061716_alphabet_cpg_model.inl"
#include "builtin_models/t_007_ont_alphabet_nucleotide_5mer_model.inl"
#include "builtin_models/t_007_ont_alphabet_nucleotide_model.inl"

// Autogenerated from convert_all_models.py
const static std::vector<PoreModel> builtin_models({
        initialize_c_p1_007_ecoli_er2925_pcr_MSssI_r9_timp_061716_alphabet_cpg_model_builtin(),
        initialize_c_p1_007_ont_alphabet_nucleotide_5mer_model_builtin(),
        initialize_c_p1_007_ont_alphabet_nucleotide_model_builtin(),
        initialize_c_p2_007_ecoli_er2925_pcr_MSssI_r9_timp_061716_alphabet_cpg_model_builtin(),
        initialize_c_p2_007_ont_alphabet_nucleotide_5mer_model_builtin(),
        initialize_c_p2_007_ont_alphabet_nucleotide_model_builtin(),
        initialize_t_007_ecoli_er2925_pcr_MSssI_r9_timp_061716_alphabet_cpg_model_builtin(),
        initialize_t_007_ont_alphabet_nucleotide_5mer_model_builtin(),
        initialize_t_007_ont_alphabet_nucleotide_model_builtin()
});


#endif
